# Generated by Django 5.2 on 2026-04-16 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('register', '注册'), ('approve_request', '审批通过'), ('reject_request', '审批拒绝'), ('role_change', '角色变更'), ('package_upload', '任务包上传'), ('package_delete', '任务包删除'), ('package_claim', '领取任务包'), ('package_submit', '提交任务包'), ('qc_claim', '领取质检任务'), ('qc_submit', '提交质检结果'), ('client_assign', '分配甲方任务'), ('client_review', '甲方审核'), ('member_delete', '删除成员'), ('org_admin_change', '组织管理员变更')], max_length=30, verbose_name='操作类型')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='涉及模型')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('details', models.TextField(blank=True, default='', verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='core_auditl_user_id_4f5b78_idx'), models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'), models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx')],
            },
        ),
    ]
