# Generated by Django 5.2 on 2025-07-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_client_clienttaskaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientTaskAccess',
        ),
    ]
