# Generated by Django 5.2 on 2025-07-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_clienttaskaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
