# Generated by Django 5.2 on 2025-07-17 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0011_qcassignment_updated_at'),
        ('user', '0005_user_raw_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTaskAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.taskpackage')),
            ],
            options={
                'unique_together': {('client', 'task_package')},
            },
        ),
    ]
