# Generated by Django 5.2 on 2026-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0015_alter_qcassignment_is_completed_and_more'),
        ('user', '0006_clienttaskaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='raw_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_org_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='clienttaskaccess',
            index=models.Index(fields=['client'], name='user_client_client__e0baa1_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttaskaccess',
            index=models.Index(fields=['task_package'], name='user_client_task_pa_46b53c_idx'),
        ),
    ]
