# Generated by Django 5.2 on 2025-07-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_taskpackage_allowed_organization_taskassignment'),
        ('user', '0002_organizationjoinrequest_roleinorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpackage',
            name='allowed_organization',
            field=models.ForeignKey(blank=True, help_text='可以领取该任务包的组织', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.organization'),
        ),
    ]
