# Generated by Django 5.2 on 2025-07-05 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_alter_taskpackage_allowed_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(upload_to='task_images/'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.taskpackage'),
        ),
    ]
