# Generated by Django 5.2 on 2025-07-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_alter_imagefile_image_alter_imagefile_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='is_labeled',
            field=models.BooleanField(default=False),
        ),
    ]
