# Generated by Django 5.2 on 2025-07-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_imagefile_is_labeled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='is_labeled',
        ),
    ]
