# Generated by Django 5.2 on 2025-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_remove_imagefile_is_labeled'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='labels',
            field=models.TextField(blank=True, help_text='多个标签用英文逗号分隔，例如：car,bus,person'),
        ),
    ]
