# Generated by Django 5.2 on 2025-07-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0007_taskpackage_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='save_format',
            field=models.CharField(choices=[('json', 'LabelMe JSON'), ('xml', 'Pascal VOC XML'), ('txt', 'YOLO TXT')], default='json', max_length=10),
        ),
    ]
