# Generated by Django 5.2 on 2025-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0009_qcassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='qc_status',
            field=models.CharField(blank=True, choices=[('pass', '合格'), ('fail', '不合格')], help_text='质检状态', max_length=10, null=True),
        ),
    ]
