# Generated by Django 5.2 on 2025-07-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0010_taskpackage_qc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
