# Generated by Django 5.2 on 2025-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0011_qcassignment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='client_review_status',
            field=models.CharField(blank=True, choices=[('pass', '通过'), ('fail', '不通过')], help_text='甲方审核状态', max_length=10, null=True),
        ),
    ]
