# Generated by Django 5.2 on 2025-07-19 06:54

import label.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0012_taskpackage_client_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(upload_to=label.models.image_upload_path),
        ),
    ]
