# Generated by Django 5.2 on 2025-07-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0013_alter_imagefile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='label_file',
            field=models.FileField(blank=True, help_text='可选标签库 JSON 文件', null=True, upload_to='label_files/'),
        ),
    ]
