# Generated by Django 5.2 on 2026-04-16 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0014_taskpackage_label_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcassignment',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='client_review_status',
            field=models.CharField(blank=True, choices=[('pass', '通过'), ('fail', '不通过')], db_index=True, help_text='甲方审核状态', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='qc_status',
            field=models.CharField(blank=True, choices=[('pass', '合格'), ('fail', '不合格')], db_index=True, help_text='质检状态', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='qcassignment',
            index=models.Index(fields=['user', 'is_completed'], name='label_qcass_user_id_08fa55_idx'),
        ),
        migrations.AddIndex(
            model_name='qcassignment',
            index=models.Index(fields=['package', 'is_completed'], name='label_qcass_package_47b4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['user', 'is_completed'], name='label_taska_user_id_c7c51f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['package', 'is_completed'], name='label_taska_package_cf5747_idx'),
        ),
    ]
